spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_management_system
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

!change to validate before moving to production
spring.jpa.hibernate.ddl-auto=update